[package]
name = "async_web_scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
tokio = { version = "1", features = ["full"] }
